"""empty message

Revision ID: ced1ad021e03
Revises: cec38cd3151d
Create Date: 2023-07-31 18:23:25.446227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced1ad021e03'
down_revision = 'cec38cd3151d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('student1', sa.Text(), nullable=False),
    sa.Column('student2', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index('ix_student_index')

    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('index', sa.TEXT(), nullable=True),
    sa.Column('월요일', sa.TEXT(), nullable=True),
    sa.Column('화요일', sa.TEXT(), nullable=True),
    sa.Column('수요일', sa.TEXT(), nullable=True),
    sa.Column('목요일', sa.TEXT(), nullable=True),
    sa.Column('금요일', sa.TEXT(), nullable=True)
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index('ix_student_index', ['index'], unique=False)

    op.drop_table('patrol')
    # ### end Alembic commands ###
